-- AlterTable
ALTER TABLE "pets" ADD COLUMN     "iv_attack" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "iv_defense" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "iv_hp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "iv_speed" INTEGER NOT NULL DEFAULT 0;
