import { Opponent, Move } from '@/stores/types/game'
import { getPokemonImage } from '@/assets/images'

// Default moves for opponents
const BASIC_MOVES: Move[] = [
  {
    id: 'tackle',
    name: 'Tackle',
    type: 'Physical',
    element: 'Normal',
    power: 40,
    accuracy: 100,
    pp: 35,
    maxPp: 35,
    description: 'A basic physical attack',
    effects: {},
  },
  {
    id: 'quick-attack',
    name: 'Quick Attack',
    type: 'Physical',
    element: 'Normal',
    power: 40,
    accuracy: 100,
    pp: 30,
    maxPp: 30,
    description: 'An attack that always strikes first',
    effects: {},
  },
]

const GRASS_MOVES: Move[] = [
  {
    id: 'vine-whip',
    name: 'Vine Whip',
    type: 'Physical',
    element: 'Grass',
    power: 45,
    accuracy: 100,
    pp: 25,
    maxPp: 25,
    description: 'Whips the foe with slender vines',
    effects: {},
  },
  {
    id: 'absorb',
    name: 'Absorb',
    type: 'Special',
    element: 'Grass',
    power: 20,
    accuracy: 100,
    pp: 25,
    maxPp: 25,
    description: 'Absorbs HP from the opponent',
    effects: { healing: 10 },
  },
]

const FIRE_MOVES: Move[] = [
  {
    id: 'ember',
    name: 'Ember',
    type: 'Special',
    element: 'Fire',
    power: 40,
    accuracy: 100,
    pp: 25,
    maxPp: 25,
    description: 'An attack that may inflict a burn',
    effects: {},
  },
  {
    id: 'flame-burst',
    name: 'Flame Burst',
    type: 'Special',
    element: 'Fire',
    power: 70,
    accuracy: 100,
    pp: 15,
    maxPp: 15,
    description: 'A powerful flame attack',
    effects: {},
  },
]

const WATER_MOVES: Move[] = [
  {
    id: 'water-gun',
    name: 'Water Gun',
    type: 'Special',
    element: 'Water',
    power: 40,
    accuracy: 100,
    pp: 25,
    maxPp: 25,
    description: 'Squirts water to attack',
    effects: {},
  },
  {
    id: 'hydro-pump',
    name: 'Hydro Pump',
    type: 'Special',
    element: 'Water',
    power: 110,
    accuracy: 80,
    pp: 5,
    maxPp: 5,
    description: 'A powerful water-type attack',
    effects: {},
  },
]

const DARK_MOVES: Move[] = [
  {
    id: 'dark-pulse',
    name: 'Dark Pulse',
    type: 'Special',
    element: 'Dark',
    power: 80,
    accuracy: 100,
    pp: 15,
    maxPp: 15,
    description: 'Releases a horrible aura',
    effects: {},
  },
  {
    id: 'shadow-ball',
    name: 'Shadow Ball',
    type: 'Special',
    element: 'Ghost',
    power: 80,
    accuracy: 100,
    pp: 15,
    maxPp: 15,
    description: 'Hurls a shadowy blob',
    effects: {},
  },
]

// Opponents are now a constant - not stored in Redux state
// This prevents caching issues and makes updates immediate
export const OPPONENTS: Opponent[] = [
  {
    id: 'opp-001',
    name: 'Oddish',
    species: 'Oddish',
    level: 5,
    difficulty: 'Easy',
    stats: { hp: 35, maxHp: 35, attack: 18, defense: 15, speed: 20 },
    moves: [...GRASS_MOVES, ...BASIC_MOVES].slice(0, 4),
    image: getPokemonImage('Oddish'),
    rewards: { xp: 50, coins: 25, items: [] },
    unlockLevel: 1,
  },
  {
    id: 'opp-002',
    name: 'Treecko',
    species: 'Treecko',
    level: 10,
    difficulty: 'Normal',
    stats: { hp: 55, maxHp: 55, attack: 28, defense: 25, speed: 22 },
    moves: [...GRASS_MOVES, ...BASIC_MOVES].slice(0, 4),
    image: getPokemonImage('Treecko'),
    rewards: { xp: 75, coins: 40, items: ['item-heal-001'] },
    unlockLevel: 5,
  },
  {
    id: 'opp-003',
    name: 'Charizard',
    species: 'Charizard',
    level: 15,
    difficulty: 'Hard',
    stats: { hp: 75, maxHp: 75, attack: 42, defense: 30, speed: 35 },
    moves: [...FIRE_MOVES, ...BASIC_MOVES].slice(0, 4),
    image: getPokemonImage('Charizard'),
    rewards: { xp: 120, coins: 75, items: ['item-heal-001', 'item-evo-001'] },
    unlockLevel: 10,
  },
  {
    id: 'opp-004',
    name: 'Blastoise',
    species: 'Blastoise',
    level: 20,
    difficulty: 'Expert',
    stats: { hp: 95, maxHp: 95, attack: 38, defense: 45, speed: 40 },
    moves: [...WATER_MOVES, ...BASIC_MOVES].slice(0, 4),
    image: getPokemonImage('Blastoise'),
    rewards: { xp: 180, coins: 120, items: ['item-heal-001', 'item-evo-001', 'item-stat-001'] },
    unlockLevel: 15,
  },
  {
    id: 'opp-005',
    name: 'Darkrai',
    species: 'Darkrai',
    level: 25,
    difficulty: 'Master',
    stats: { hp: 120, maxHp: 120, attack: 55, defense: 50, speed: 50 },
    moves: [...DARK_MOVES, ...BASIC_MOVES].slice(0, 4),
    image: getPokemonImage('Darkrai'),
    rewards: { xp: 250, coins: 200, items: ['item-heal-001', 'item-evo-001', 'item-stat-001'] },
    unlockLevel: 20,
  },
]
